### PR TITLE
Brand new galleries

### PR DESCRIPTION
**Pull request by zahanm**
- galleries for ios and android
- using `gulp` for build
- sweet es6 and flow types in the js transformed by babel

### CODE REVIEW

**Comment by zahanm** [comment]
The two commands you now need to run for development (in separate tabs)

``` sh
$ gulp server
$ gulp watch
```

**Comment by zahanm** [comment]
home page

android

ios

**Comment by vibhabamba** [comment]
Looks good.

**Comment by vibhabamba** [comment]
galleries are fading beautifully. Thank you for screenshots.

**Pull request merged**
